stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - raphael_tag      # <-- change to your runner's tag
  script:
    - cd Backend/trivia        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - raphael_cicd
    changes:
      - Backend/trivia/*


maven-test:             
  stage: maventest
  tags:
    - raphael_tag     # <-- change to your runner's tag
  script:
    - cd Backend/trivia       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - raphael_cicd
    changes:
      - Backend/trivia/*
